# fly.toml app configuration file
# Docs: https://fly.io/docs/reference/configuration/

app = "REPLACE_WITH_YOUR_APP_NAME"
primary_region = "sin"

[build]

[env]
  PORT = "8000"

[[services]]
  protocol = "tcp"
  internal_port = 8000

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [[services.http_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "10s"
    method = "get"
    path = "/healthz"
    protocol = "http"
    tls_skip_verify = false

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"

